apiVersion: v1
kind: Pod
metadata:
  name: app-posts
  namespace: nestjs-app
  labels:
    application: app-posts-pod
spec:
  containers:
    - name: pickly-posts
      image: sahlkhalifa/app-posts:4.0
      # command: ["node"]
      # args: ["dist/src/main.js"]
      env:
        - name: APP_NAME
          value: "app-posts"
        - name: DB_DATABASE
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "123456"
        - name: DB_HOST
          value: "postgres.nestjs-app"
      #   - name: POSTS_URL
      #     value: http://pickly-posts.pickly
      #   - name: NOTIFICATIONS_URL
      #     value: http://pickly-notifications.pickly
      #   - name: VOTES_URL
      #     value: http://pickly-votes.pickly
      ports:
        - name: web
          containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: app-votes
  namespace: nestjs-app
  labels:
    application: app-votes-pod
spec:
  containers:
    - name: app-votes
      image: sahlkhalifa/app-posts:4.0
      env:
        - name: APP_NAME
          value: "app-votes"
      #   - name: POSTS_URL
      #     value: http://pickly-posts.pickly
      #   - name: NOTIFICATIONS_URL
      #     value: http://pickly-notifications.pickly
      #   - name: VOTES_URL
      #     value: http://pickly-votes.pickly
      ports:
        - name: web
          containerPort: 3000
          protocol: TCP