# This workflow will build a docker image from the app and push it to docker hub whenever any push on deployment branch
name: Node.js CI

on:
  push:
    branches: [ deployment ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.prepare.outputs.sha }}
      version: ${{ steps.prepare.outputs.version }}
      image: sahlkhalifa/app
      dockerfile: Dockerfile
    steps:
      - uses: actions/checkout@v2
      - id: prepare
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          echo "::set-output name=version::$(git rev-parse --short=4 HEAD)"
  build-docker_image:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - id: install-dependencies
        run: yarn

      # - id: run-unit-tests
      #   run: yarn test
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{needs.prepare.outputs.image}}
          dockerfile: ${{needs.prepare.outputs.dockerfile}}
          tags: ${{needs.prepare.outputs.version}}
